version: "2"
plugins:
  fixme:
    enabled: true
  git-legal:
    enabled: true
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
  markdownlint:
    enabled: true
  shellcheck:
    enabled: true
