name: Validate

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    container: lingrino/ci:latest
    steps:
      - name: Code - Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Go fmt
        run: test -z $(gofmt -l -w -s ./)
      - name: Run Tests
        run: go test -cover -race -v ./...
      - name: Upload Coverage
        uses: paambaati/codeclimate-action
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: go test -cover -coverprofile=c.out -covermode=atomic ./...
