name: Validate

on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    container: lingrino/ci:latest
    steps:
      - name: Code - Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set Environment Variables
        run: |
          echo "::set-env name=GIT_BRANCH::${GITHUB_SHA##*/}"
          echo "::set-env name=GIT_COMMIT_SHA::${GITHUB_SHA}"
      - name: Go fmt
        run: test -z $(gofmt -l -w -s ./)
      - name: Prep Coverage
        run: |
          cc-test-reporter before-build
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      - name: Run Tests
        run: go test -cover -coverprofile=c.out -covermode=atomic -race -v ./...
      - name: Upload Coverage
        run: |
          cc-test-reporter after-build --coverage-input-type gocov
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
